"""add current field

Revision ID: 64ec48905716
Revises: a1f531df0b7f
Create Date: 2024-10-25 11:20:25.975942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64ec48905716'
down_revision: Union[str, None] = 'a1f531df0b7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('current_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'current_date')
    # ### end Alembic commands ###
